build:
	zip tutorial_files.zip README.md notebook.html notebook.ipynb
	cp notebook.html index.html

clean:
	rm peptide.crd peptide.pdb peptide.top
	rm md.in md.nc md.out md.rst
	rm leap.in leap.log
	rm min.in min.rst7 mdinfo md.nc mdout
